apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: backend
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 5000       # Service port
      targetPort: 5000 # Container port
      protocol: TCP
