
backend:
  image: ""
  tag: ""
  replicas: 1

frontend:
  image: ""
  tag: ""
  replicas: 1

ingress:
  host: ecom.damdav.online
  certificateArn: arn:aws:acm:us-east-2:503876630944:certificate/48591f7e-c999-4547-8bf9-5337a7b6b945

