backend:
  image: ""
  tag: ""
  replicas: 1

frontend:
  image: ""
  tag: ""
  replicas: 1

ingress:
  enabled: true
  host: ecom.damdav.online
  ingressClassName: nginx   # <--- NEW
  certificateArn: ""        # not needed for NGINX, optional
